FROM node:14.15.4-alpine3.12

# Set working directory
WORKDIR /app

COPY ./package*.json ./
COPY ./prisma ./prisma/

COPY ./.developement.env ./

COPY ./tsconfig.json ./
COPY ./ .

# Install dependencies
RUN rm -rf .env && mv .developement.env .env
RUN npm install
RUN npx prisma generate

EXPOSE 3000

CMD npx prisma migrate dev && npm run dev