FROM node

WORKDIR /app

# COPY package.json and package-lock.json files
COPY package*.json ./


# COPY tsconfig.json file
COPY tsconfig.json ./

# COPY
COPY . .

RUN npm install

# Run and expose the server on port 3000
EXPOSE 3000

# A command to start the server
CMD npm run dev