build:
	pip install -r requirements.txt
	pip uninstall opencv-python-headless

test:
	/bin/python3 src/main.py

dem1:
	/bin/python3 src/demarcacao.py 1 0

dem2:
	/bin/python3 src/demarcacao.py 2 1

dem3:
	/bin/python3 src/demarcacao.py 3 2