# Use a base de imagem do Eclipse MQTT
FROM eclipse-mosquitto

# Copie os arquivos de configuração MQTT para o contêiner
COPY mosquitto.conf /mosquitto/config/mosquitto.conf

# Exponha a porta MQTT padrão
EXPOSE 1883
