init:
	pip install -r requirements.txt

start:
	/bin/python3 /home/fernando/project/AutoPark/PlateDetection/src/main.py

publish:
	/bin/python3 /home/fernando/project/AutoPark/PlateDetection/src/mqtt_mock.py

test0:
	/bin/python3 /home/fernando/project/AutoPark/PlateDetection/src/test.py 0

test1:
	/bin/python3 /home/fernando/project/AutoPark/PlateDetection/src/test.py 1

test2:
	/bin/python3 /home/fernando/project/AutoPark/PlateDetection/src/test.py 2